### ISSUE TITLE
Error en todo reiniciador

### ISSUE THREAD

**Issue by neurotic** [hhkaos/reiniciador#2]
Al entrar me sale este error (y también en signup y supongo que en todas las páginas)

Ha habido un error

Disculpa las molestias, acabo de registrar el error y de notificarlo al administrador. De todos modos si quieres puedes revisar los bugs reportados aquí.

Seguro que es una tontería.

**Comment by hhkaos** [comment]
Perdonad chicos! que no vi estos mensajes! (voy a ver si me llegaron a la bandeja de correo). Al final era un fallo con la configuración de Apache creo. Ya no os falla verdad?
